export type SplitDirection = "horizontal" | "vertical";

export interface PaneNode {
  id: string;
  type: "leaf" | "split";
  direction?: SplitDirection;
  size: number;
  children?: PaneNode[];
  sessionId?: number;
  configId?: string;
}

export interface SavedWindow {
  id: string;
  name: string;
  rootPane: PaneNode;
}

export interface SavedWindowConfig extends SavedWindow {}

export interface SavedWorkspace {
  id: string;
  name: string;
  windows: SavedWindow[];
}

export interface Window {
  id: string;
  name: string;
  rootPane: PaneNode;
  activePaneId: string | null;
  windowType?: "terminal" | "init";
}

export interface Workspace {
  id: string;
  name: string;
  windows: Window[];
  activeWindowId: string | null;
  sessionIds: number[];
  savedWorkspaceId?: string;
}

// ---------------------------------------------------------------------------
// Session — unchanged except type is explicitly "local" | "ssh"
// ---------------------------------------------------------------------------

export interface Session {
  id: number;
  configId: string;
  name: string;
  type: "local" | "ssh";
  is_connected: boolean;
  session_type: SessionType;
}

export type SessionType =
  | { type: "local"; shell: string; cwd: string }
  | { type: "ssh"; host: string; port: number; user: string };

// ---------------------------------------------------------------------------
// Backend adapter types — kept for sessionService.ts and command interfaces
// ---------------------------------------------------------------------------

export interface LocalSessionConfig {
  shell?: string;
  cwd?: string;
  args?: string[];
  system: SystemConfig;
  terminal: TerminalConfig;
}

export interface SSHSessionConfig {
  host: string;
  port: number;
  username: string;
  auth_type: "password" | "key";
  password?: string;
  key_file?: string;
  passphrase?: string;
  system: SystemConfig;
  terminal: TerminalConfig;
}

// ---------------------------------------------------------------------------
// Phase 1 layered session config types
// ---------------------------------------------------------------------------

/** Extended session type kind supporting future transport types. */
export type SessionTypeKind = "local" | "ssh" | "tcp" | "serial" | "telnet";

export interface LocalSessionSpec {
  shell?: string;
  cwd?: string;
  args?: string[];
}

export interface SshSessionSpec {
  host: string;
  port: number;
  username: string;
  auth_type: "password" | "key";
  password?: string;
  key_file?: string;
  passphrase?: string;
}

/** Placeholder — tcp/serial/telnet creation logic is out of scope for Phase 1. */
export interface TcpSessionSpec {}

export interface SerialSessionSpec {}

export interface TelnetSessionSpec {}

export type SessionSpec = LocalSessionSpec | SshSessionSpec | TcpSessionSpec | SerialSessionSpec | TelnetSessionSpec;

export type SystemProfile = "windows" | "linux" | "wsl" | "ssh" | "none";

export interface SystemConfig {
  newline: string;
  terminalType: string;
  charset: string;
  backspace: string;
  delete: string;
  mouseScroll: string;
  signalKey: string;
}

export interface TerminalConfig {
  scrollbackLines: number;
  autoLogPath: string;
  highlightKeywords: string;
}

/**
 * Layered saved session config (Phase 1).
 *
 * Replaces the flat shape. The Phase 1 frontend uses this exclusively.
 * The backend adapter (Phase 2) will extract the legacy flat config from
 * `spec` + `system` when calling Rust commands.
 */
export interface SavedSessionConfig {
  id: string;
  name: string;
  type: SessionTypeKind;
  groupId: string | null;
  spec: SessionSpec;
  system: SystemConfig;
  terminal: TerminalConfig;
}

/** Alias for configs being created (id is generated by the action, not the dialog). */
export type CreateSavedSessionConfig = Omit<SavedSessionConfig, "id">;

// ---------------------------------------------------------------------------
// SessionGroup — unchanged
// ---------------------------------------------------------------------------

export interface SessionGroup {
  id: number;
  name: string;
  configIds: string[];
  collapsed: boolean;
}
